### PR TITLE
Move site-packages to dist-packages

### PR DESCRIPTION
**Pull request by zek**
Issue #6

### CODE REVIEW

**Comment by knightebsuku** [comment]
Does this work?
what happens if there is an existing project?

I've not had the chance to look at this yet. Will probably look at it this evening.

**Comment by zek** [comment]
This is my solution for my application.

I don't know if there are any possibility for files in dist-packages before moving. 

I compiled it in python3.6 and it works on python3.5 and python3.6

**Review by knightebsuku — APPROVED** [review]
OK

**Comment by knightebsuku** [comment]
Nice, just tested. it works :-)

**Comment by zek** [comment]
Cool 👍

BTW We may also put an option to ship python with package. So we can remove
python dependency and we can be sure it is always runs in specific python
version.

Just an idea. If you think it's a good idea, I may look if it is possible
to do with virtual env.
27 Tem 2018 Cum, saat 16:18 tarihinde Lunga Mthembu <
notifications@github.com> şunu yazdı:

**Comment by knightebsuku** [comment]
In this case, I don't this its really necessary to ship a python version with the package. qoqa is only targeting debian based systems which all have python3 installed by default. Your fix of moving to dist-packages will allow for various versions py3 to work :-)

There might be edge cases where this might break, but we'd need to see/understand that edge case first to see whether packaging python itself would be the be best and only solution

**Comment by zek** [comment]
You have a point. Edge case would be if we need specific python version and
user doesn't have it.

Then user should upgrade os or find a way to install specific python
version from Google.

But for me there is no need for it. So We will wait and see :)

Thanks for this project. You saved so much time for me.
27 Tem 2018 Cum, saat 17:21 tarihinde Lunga Mthembu <
notifications@github.com> şunu yazdı:

**Pull request merged**
